name: build-em-dosbox
on:
  push:
    paths-ignore:
      - 'dist/**'
      - '**/README.md'
jobs:
  job_id:
    name: build 
    runs-on: ubuntu-latest
    steps:
        - name: Install GNU Autotools
          run: sudo apt-get install autotools-dev autoconf automake
        - name: Install Emscripten [latest]
          uses: mymindstorm/setup-emsdk@v7
          with:
            version: 'latest'
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Detailing Versions
          run: |
            emcc -v
        - name: Using Configure Flags
          run: echo "./configure --enable-wasm --disable-opengl --host=none-none-none"
        - name: Running Autogen
          run: |
            chmod +x autogen.sh
            ./autogen.sh
        - name: Configure and Build RELEASE
          run: |
            echo "Building RELEASE Version [No Debugging Information]"
            export EMMAKEN_CFLAGS="-O3"
            emconfigure ./configure --enable-wasm --disable-opengl --host=none-none-none
            emmake make
            cp src/dosbox.html src/dosbox.js src/dosbox.wasm src/packager.py dist/release/
            emmake make clean
        - name: Configure and Build DEBUG
          run: |
            echo "Building DEBUG Version [Extra Debugging Information]"
            export EMMAKEN_CFLAGS="-g --profiling --profiling-funcs"
            sed -i 's/TOTAL_MEMORY=134217728/TOTAL_MEMORY=268435456/g' src/Makefile
            emconfigure ./configure --enable-wasm --disable-opengl --host=none-none-none
            emmake make
            cp src/dosbox.html src/dosbox.js src/dosbox.wasm src/packager.py dist/debug/
        - name: Commit re-Distributables
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add dist/debug/dosbox.html dist/debug/dosbox.js dist/debug/dosbox.wasm dist/debug/packager.py
            git add dist/release/dosbox.html dist/release/dosbox.js dist/release/dosbox.wasm dist/release/packager.py
            git commit -m "Update dist commit `git rev-parse --verify HEAD`"
        - name: Publish Artifacts to Dist/
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: "main"
