name: build-em-dosbox
on:
  push:
    paths-ignore:
      - 'dist/**'
      - '**/README.md'
jobs:
  job_id:
    name: build 
    runs-on: ubuntu-latest
    steps:
        - name: Install GNU Autotools
          run: sudo apt-get install autotools-dev autoconf automake
        - name: Install Emscripten [latest]
          uses: mymindstorm/setup-emsdk@v6
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Using Configure Flags
          run: echo "./configure --enable-wasm --disable-opengl --host=none-none-none"
        - name: Configure and Build
          run: |
            chmod +x autogen.sh
            ./autogen.sh
            emconfigure ./configure --enable-wasm --disable-opengl --host=none-none-none
            emmake make
            cp src/dosbox.html src/dosbox.js src/dosbox.wasm src/packager.py dist/
        - name: Commit re-Distributables
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add dist/dosbox.html dist/dosbox.js dist/dosbox.wasm dist/packager.py
            git commit -m "Update dist commit `git rev-parse --verify HEAD`"
        - name: Publish Artifacts to Dist/
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
