name: build-em-dosbox
on:
  push:
    paths-ignore:
      - 'dist/**'
      - '**/README.md'
jobs:
  job_id:
    name: build 
    runs-on: ubuntu-latest
    steps:
        - name: Install GNU Autotools
          run: sudo apt-get install autotools-dev autoconf automake
        - name: Install Emscripten [latest]
          uses: mymindstorm/setup-emsdk@v6
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Using Configure Flags
          run: echo "./configure --enable-wasm --disable-opengl --host=none-none-none"
        - name: Configure and Build
          run: |
            chmod +x autogen.sh
            ./autogen.sh
            emconfigure ./configure --enable-wasm --disable-opengl --host=none-none-none
            emmake make
            cp src/dosbox.html src/dosbox.js src/dosbox.wasm packager.py dist/
        - name: Publish Artifacts to Dist/
          uses: seanmiddleditch/gha-publish-to-git@v2
          with:
            branch: main
            github_token: '${{ secrets.GITHUB_TOKEN  }}'
            github_pat: '${{ secrets.GH_PAT }}'
            source_folder: dist
          if: success() && github.event == 'push'
